server:
  port: 8181

spring:
  resources:
    #    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,classpath:/html,file:///home/distribution_pro/html
    static-locations: file:///home/distribution_pro/html
  #    static-locations: file:///mnt/www/html
  datasource:
    url: jdbc:mysql://120.27.239.215:3333/shoptest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: shop
    password: 7887Cdma!
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gtzn.digitcard.model

mybatis-plus:
  configuration:
    #    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml

swagger:
  production: false
  basic:
    enable: true
    username: 123
    password: 12345

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


